project:
  type: website
  output-dir: docs
exectute:
  echo: true
website:
  title: "Introduction to Computational Economics"
  sidebar:
      style: "docked"
      search: true
      contents:
        - section: "Slides"
          contents:
            - slides/introduction.qmd
            - slides/convergence.qmd
            - slides/optimization.qmd
            - slides/differentiation.qmd

        - section: "Tutorials"
          contents:
            - tutorials/2_solow_correction.ipynb
            - tutorials/3_Optimization_correction.ipynb
            - tutorials/5_automatic_differentiation_correction.ipynb

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



