project:
  type: website
execute:
  echo: true
website:
  title: "Introduction to Computational Economics"
  sidebar:
      style: "docked"
      search: true
      contents:
        - section: "Slides"
          contents:
            - slides/session_introduction/index.qmd
            - slides/session_convergence/index.qmd
            - slides/session_optimization/index.qmd
            - slides/session_perturbation/index.qmd
            - slides/session_ddp/index.qmd


        - section: "Tutorials"
          contents:
            - tutorials/1_1_Julia_Basics.ipynb
            - tutorials/2_solow.ipynb
            - tutorials/3_Optimization.ipynb
            - tutorials/7_discrete_dynamic_programming.ipynb
            # - tutorials/6_automatic_differentiation.ipynb
            # - tutorials/homework.ipynb

        - section: "Pushups"
          contents:
            - pushups/1_epidemiology.ipynb
            - pushups/2_Optimization_pushups.ipynb
        
        - section: "Coursework"
          contents:
            - coursework/coursework_1.ipynb
            - coursework/coursework_2.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



